## ***Introduction to Numpy***

**week 2 day 7-8**

**What is NumPy?**<br>
<br>
NumPy, which stands for Numerical Python, is a powerful library for numerical and mathematical operations in Python.<br>
It provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on these arrays.<br>


Key Features:

Efficient and fast operations on arrays.<br>
Mathematical functions for operations on entire arrays without the need for explicit loops.<br>
Tools for working with arrays, including indexing, slicing, and reshaping.<br>
Linear algebra, statistical, and random number capabilities.<br>

### **NumPy Arrays (numpy.array):**


Creating Arrays:

The fundamental data structure in NumPy is the numpy.array. It is similar to Python lists but optimized for numerical operations.<br>
Arrays can be created using the numpy.array function.


In [2]:
import numpy as np

# Creating a NumPy array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


**Array Attributes:**

Arrays have several attributes that provide information about their structure:<br>
* shape: Tuple representing the dimensions of the array.<br>
* dtype: Data type of the elements in the array (e.g., int, float).<br>
* size: Total number of elements in the array.<br>



In [6]:
# Array attributes
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Size:", arr.size)


Shape: (5,)
Data Type: int32
Size: 5


### **Array Creation and Attributes:**




**Creating Arrays:**

NumPy provides several functions for creating arrays, such as np.zeros, np.ones, and np.arange.<br>
You can create arrays with specified shapes and fill them with zeros, ones, or a range of values.

In [14]:
# Creating arrays
zeros_arr = np.zeros((2, 3))  # 2x3 array filled with zeros
ones_arr = np.ones((3, 3))    # 3x3 array filled with ones
range_arr = np.arange(0, 10, 2)  # Array with values from 0 to 10 (exclusive) with a step of 2

print(zeros_arr,zeros_arr.shape)
print(ones_arr,ones_arr.shape)
print(range_arr,range_arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[0 2 4 6 8] (5,)


**Array Attributes:**

The attributes of NumPy arrays provide essential information about the array's structure.<br>
These attributes help you understand the shape, size, and data type of the array.

In [5]:
# Array attributes
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print("Shape:", arr.shape)    # (2, 3)
print("Data Type:", arr.dtype)  # int64
print("Size:", arr.size)      # 6


[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Data Type: int32
Size: 6


### **Array Indexing and Slicing:**


**Indexing:**

NumPy arrays support zero-based indexing, similar to Python lists.<br>
Elements can be accessed using square brackets and indices.

In [6]:
# Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])   # Access the first element
print(arr[-1])  # Access the last element


1
5


**Slicing:**

NumPy allows you to create subarrays using slicing. Slicing is a powerful mechanism for extracting specific portions of an array.

In [7]:
# Slicing
arr = np.array([1, 2, 3, 4, 5])
subset = arr[1:4]  # Elements from index 1 to 3
print(subset)


[2 3 4]


### Exercises

In [14]:
# Array Operations:

# Create two NumPy arrays of the same shape (e.g., 3x3).

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Perform element-wise addition, subtraction, multiplication, and division on these arrays.
# Print the results for each operation.

print(array1+array2)
print(array1-array2)
print(array1*array2)
print(array1/array2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# Array Reshaping:

# Create a NumPy array with 12 elements (e.g., using np.arange(12)).
arr_range = np.arange(0,12)
print(arr_range)

# Reshape the array into a 3x4 matrix.
arr_range = arr_range.reshape(3,4)
print(arr_range)

# Reshape the array into a vector again.
arr_range = arr_range.reshape(12,)
print(arr_range)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [27]:
# Statistical Operations:

# Generate a random 2x4 array using np.random.rand.
arr_rand = np.random.rand(2,4)
print(arr_rand)

# Calculate the mean, median, and standard deviation of the array.
print('The maen is', np.mean(arr_rand))
print('The standard deviation is', np.std(arr_rand))



[[0.92983696 0.43741748 0.01590942 0.95706932]
 [0.91198016 0.93069796 0.25423793 0.44569327]]
The maen is 0.6103553146053258
The standard deviation is 0.3451598676746897


In [32]:
# Boolean Indexing:

# Create a NumPy array with values from 1 to 10.
arr_1to10 = np.arange(0,10)

# Use boolean indexing to select and print only the even numbers from the array.
condition = (arr_1to10 % 2 == 0) # this is a boolean indexing
print(condition) 

# Passing the boolean indexing to select the values
even_numbers = arr_1to10[condition]
print(even_numbers)

[ True False  True False  True False  True False  True False]
[0 2 4 6 8]


In [38]:
# Matrix Multiplication:

# Create two matrices (2x3 and 3x4) using NumPy arrays.
matrix1 = np.random.rand(2,3)
matrix2 = np.random.rand(3,4)

# Perform matrix multiplication using the np.dot function.
matrix_prod = np.dot(matrix1,matrix2)

# Print the resulting matrix.
print(matrix_prod) 

[[0.65648183 0.25728878 0.76940175 0.36477796]
 [0.88955879 0.44126269 0.99993141 0.52682289]]
