## ***introduction to Numpy***

**week 2 day 7-8**

**What is NumPy?**<br>
<br>
NumPy, which stands for Numerical Python, is a powerful library for numerical and mathematical operations in Python.<br>
It provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on these arrays.<br>


Key Features:

Efficient and fast operations on arrays.<br>
Mathematical functions for operations on entire arrays without the need for explicit loops.<br>
Tools for working with arrays, including indexing, slicing, and reshaping.<br>
Linear algebra, statistical, and random number capabilities.<br>

### **NumPy Arrays (numpy.array):**


Creating Arrays:

The fundamental data structure in NumPy is the numpy.array. It is similar to Python lists but optimized for numerical operations.<br>
Arrays can be created using the numpy.array function.


In [5]:
import numpy as np

# Creating a NumPy array from a list
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


**Array Attributes:**

Arrays have several attributes that provide information about their structure:<br>
* shape: Tuple representing the dimensions of the array.<br>
* dtype: Data type of the elements in the array (e.g., int, float).<br>
* size: Total number of elements in the array.<br>



In [6]:
# Array attributes
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Size:", arr.size)


Shape: (5,)
Data Type: int32
Size: 5


### **Array Creation and Attributes:**

Creating Arrays:

NumPy provides several functions for creating arrays, such as np.zeros, np.ones, and np.arange.<br>
You can create arrays with specified shapes and fill them with zeros, ones, or a range of values.

In [14]:
# Creating arrays
zeros_arr = np.zeros((2, 3))  # 2x3 array filled with zeros
ones_arr = np.ones((3, 3))    # 3x3 array filled with ones
range_arr = np.arange(0, 10, 2)  # Array with values from 0 to 10 (exclusive) with a step of 2

print(zeros_arr,zeros_arr.shape)
print(ones_arr,ones_arr.shape)
print(range_arr,range_arr.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)
[0 2 4 6 8] (5,)
